import { type Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        islamic: ["Islamic Relief", "sans-serif"],
        sans: ["Lato", "sans-serif"],
        marker: ["Lumios Marker", "cursive"],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        grey: {
          "black": "var(--color-grey-black)",
          "grey": "var(--color-grey-grey)",
          "inactive": "var(--color-grey-inactive)",
          "divider": "var(--color-grey-divider)",
          "bg-light": "var(--color-grey-bg-light)",
          "bg-dark": "var(--color-grey-bg-dark)",
          "white": "var(--color-grey-white)",
        },
        primary: {
          DEFAULT: "var(--color-primary)",
          main: "var(--color-primary)",
          dark: "var(--color-primary-dark)",
          surface: "var(--color-primary-surface)",
          divider: "var(--color-primary-divider)",
          light: "var(--color-primary-light)",
          lighter: "var(--color-primary-lighter)",
        },
        teal: {
          DEFAULT: "var(--color-teal)",
          main: "var(--color-teal)",
          dark: "var(--color-teal-dark)",
          surface: "var(--color-teal-surface)",
          divider: "var(--color-teal-divider)",
          light: "var(--color-teal-light)",
          lighter: "var(--color-teal-lighter)",
        },
        royal: {
          DEFAULT: "var(--color-royal)",
          main: "var(--color-royal)",
          dark: "var(--color-royal-dark)",
          surface: "var(--color-royal-surface)",
          divider: "var(--color-royal-divider)",
          light: "var(--color-royal-light)",
          lighter: "var(--color-royal-lighter)",
        },
        green: {
          DEFAULT: "var(--color-green)",
          main: "var(--color-green)",
          dark: "var(--color-green-dark)",
          surface: "var(--color-green-surface)",
          divider: "var(--color-green-divider)",
          light: "var(--color-green-light)",
          lighter: "var(--color-green-lighter)",
        },
        yellow: {
          DEFAULT: "var(--color-yellow)",
          main: "var(--color-yellow)",
          dark: "var(--color-yellow-dark)",
          surface: "var(--color-yellow-surface)",
          divider: "var(--color-yellow-divider)",
          light: "var(--color-yellow-light)",
          lighter: "var(--color-yellow-lighter)",
        },
        red: {
          DEFAULT: "var(--color-red)",
          main: "var(--color-red)",
          dark: "var(--color-red-dark)",
          surface: "var(--color-red-surface)",
          divider: "var(--color-red-divider)",
          light: "var(--color-red-light)",
          lighter: "var(--color-red-lighter)",
        },
        purple: {
          DEFAULT: "var(--color-purple)",
          main: "var(--color-purple)",
          dark: "var(--color-purple-dark)",
          surface: "var(--color-purple-surface)",
          divider: "var(--color-purple-divider)",
          light: "var(--color-purple-light)",
          lighter: "var(--color-purple-lighter)",
        },
        sunGlow: {
          DEFAULT: "var(--color-sunGlow)",
          main: "var(--color-sunGlow)",
          dark: "var(--color-sunGlow-dark)",
          surface: "var(--color-sunGlow-surface)",
          divider: "var(--color-sunGlow-divider)",
          light: "var(--color-sunGlow-light)",
          lighter: "var(--color-sunGlow-lighter)",
        },
        overlayWhite: {
          5: "var(--color-overlayWhite-5)",
          10: "var(--color-overlayWhite-10)",
          20: "var(--color-overlayWhite-20)",
          40: "var(--color-overlayWhite-40)",
          60: "var(--color-overlayWhite-60)",
          80: "var(--color-overlayWhite-80)",
        },
        overlayBlack: {
          5: "var(--color-overlayBlack-5)",
          10: "var(--color-overlayBlack-10)",
          20: "var(--color-overlayBlack-20)",
          40: "var(--color-overlayBlack-40)",
          60: "var(--color-overlayBlack-60)",
          80: "var(--color-overlayBlack-80)",
        },
      },
    },
  },
  plugins: [],
};
export default config;
